
name: Java CI with Gradle

on:
  workflow_run:
    workflows: [IAC deployment] 
    types: [completed]
    branches: [master]

#starting job
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2
        
      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
                  
      - name: Step3 - Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: build
          
      - run: |
          ls '${{ github.workspace }}/build/libs'
          cp '${{ github.workspace }}/build/libs/gs-spring-boot-0.1.0.jar' .
      - name: Step 6 - Deploy to CF
        uses: citizen-of-planet-earth/cf-cli-action@master
        with:
          cf_api: https://api.cf.ap21.hana.ondemand.com
          cf_username: ramyaravindra999@gmail.com
          cf_password: Azuredevops@123
          cf_org: 6fece677trial
          cf_space: prod
          command: |
            cf push MY-APP2 –p '${{ github.workspace }}/build/libs'/gs-spring-boot-0.1.0.jar
            cf push gs-spring-boot-0.1.0.jar
          run: ls

