 
name: Pipeline
on:
  push:
    branches:
      - branch_env_test
 
#starting buildjob
jobs:
  CI:
    runs-on: ubuntu-latest
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2
     
      - name: Step 2 - 
        run: |
          echo "$GITHUB_REF_NAME"
          echo "$GITHUB_REF"
          echo "$GITHUB_ACTOR"
          echo "$GITHUB_ACTION_REPOSITORY"
          echo "$GITHUB_ACTIONS"
          

      - name: Get the current branch name
        run: echo "::set-output name=branch::${GITHUB_REF#refs/heads/}"
        id: myref
        
      - name: print
        run: |
          echo "${{steps.myref.outputs.branch}}"

