
name: Pipeline
on:
  workflow_run:
    workflows: [IAC deployment] 
    types: [completed]
    branches: [master]

#starting buildjob
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Step 1 - Checkout main branch from GitHub 
        uses: actions/checkout@v2
        
      # Runs a single command using the runners shell
      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
                  
      - name: Step3 - Build with Gradle
        uses: gradle/gradle-build-action@4137be6a8bf7d7133955359dbd952c0ca73b1021
        with:
          arguments: build
          
      - name: Step4 checking build file
        run: |
          ls '${{ github.workspace }}/build/libs'          

      - name: Step5 Jfrog artifactory
        uses: jfrog/setup-jfrog-cli@v2.0.0
      - run: jfrog rt ping https://www.google.co.in/
        
      - name: Step 6 - Deploy to CF
        uses: jhunt/cf-push@v1
        with:
          api: https://api.cf.ap21.hana.ondemand.com
          username: ramyaravindra999@gmail.com
          password: Azuredevops@123
          org: 6fece677trial
          space: prod
          run : pwd
          manifest: manifest.yml




