name: elk
on:
  push:
    branches: branch_elk
jobs:
  run-demo-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    #- name: Check http status code of production site
     # uses: lakuapik/gh-actions-http-status@v1
     # with:
     #   sites: '["http://github.com", "https://es-6b7b6def.internal.na1.cluster.hsdp.io:443"]'
     #   expected: '[301, 200]'
        
    - name: Upload GitHub Action workflows logs to elastic
      uses: shahargl/upload-github-workflow-logs-to-elastic@1.0.13
      with:
       github_token: "${{ secrets.ELK_GITHUB_TOKEN }}"
       github_org: "org-Santhosh"
       github_repository: "java-hello-world-with-gradle"
       github_run_id: "${{ github.run_id }}"
       elastic_host: "${{ secrets.ELASTIC_HOST }}"
       elastic_api_key_id: "${{ secrets.ELASTIC_KEY_ID }}"
       elastic_api_key: "${{ secrets.ELASTIC_API_KEY }}"
       elastic_index: "ci-cd"
