#creating IAC deployment
name: IAC deployment
#creating event whenever commit happens it will trigger
on:
  push:
    branches: [ master ]
#creating job
jobs:
  IAC:
    #selecting ubuntu runner
    runs-on: ubuntu-latest 
    steps:
      - name: IAC
        run: echo "infrastructure setup"
